// <auto-generated />
using System;
using MVC_ComponentesCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_ComponentesCodeFirst.Migrations
{
    [DbContext(typeof(ComponenteContext))]
    partial class ComponenteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Componentes.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calor")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<int>("Coste")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Megas")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDeSerie")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("OrdenadorId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenadorId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calor = 10,
                            Cores = 9,
                            Coste = 134,
                            Descripcion = "Procesador Intel i7",
                            Megas = 0L,
                            NumeroDeSerie = "789-XCS",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            Calor = 12,
                            Cores = 10,
                            Coste = 138,
                            Descripcion = "Procesador Intel i7",
                            Megas = 0L,
                            NumeroDeSerie = "789-XCD",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            Calor = 22,
                            Cores = 11,
                            Coste = 138,
                            Descripcion = "Procesador Intel i7",
                            Megas = 0L,
                            NumeroDeSerie = "789-XCT",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            Calor = 10,
                            Cores = 0,
                            Coste = 100,
                            Descripcion = "Banco de Memoria SDRAM",
                            Megas = 512L,
                            NumeroDeSerie = "879FH",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Calor = 15,
                            Cores = 0,
                            Coste = 125,
                            Descripcion = "Banco de Memoria SDRAM",
                            Megas = 1024L,
                            NumeroDeSerie = "879FH-L",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 6,
                            Calor = 24,
                            Cores = 0,
                            Coste = 150,
                            Descripcion = "Banco de Memoria SDRAM",
                            Megas = 1024L,
                            NumeroDeSerie = "879FH-T",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 7,
                            Calor = 10,
                            Cores = 0,
                            Coste = 50,
                            Descripcion = "DiscoDuro SanDisk",
                            Megas = 512000L,
                            NumeroDeSerie = "789-XX",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Calor = 29,
                            Cores = 0,
                            Coste = 90,
                            Descripcion = "DiscoDuro SanDisk",
                            Megas = 1024000L,
                            NumeroDeSerie = "789-XX-2",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 9,
                            Calor = 39,
                            Cores = 0,
                            Coste = 128,
                            Descripcion = "DiscoDuro SanDisk",
                            Megas = 2048000L,
                            NumeroDeSerie = "789-XX-3",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 10,
                            Calor = 30,
                            Cores = 10,
                            Coste = 78,
                            Descripcion = "Procesador Ryzen AMD",
                            Megas = 0L,
                            NumeroDeSerie = "797-X",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 11,
                            Calor = 30,
                            Cores = 29,
                            Coste = 178,
                            Descripcion = "Procesador Ryzen AMD",
                            Megas = 0L,
                            NumeroDeSerie = "797-X2",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 12,
                            Calor = 60,
                            Cores = 34,
                            Coste = 278,
                            Descripcion = "Procesador Ryzen AMD",
                            Megas = 0L,
                            NumeroDeSerie = "797-X3",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 13,
                            Calor = 35,
                            Cores = 0,
                            Coste = 37,
                            Descripcion = "Disco Mecánico Patatin",
                            Megas = 250L,
                            NumeroDeSerie = "788-fg",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 14,
                            Calor = 35,
                            Cores = 0,
                            Coste = 67,
                            Descripcion = "Disco Mecánico Patatin",
                            Megas = 250L,
                            NumeroDeSerie = "788-fg-2",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 15,
                            Calor = 35,
                            Cores = 0,
                            Coste = 97,
                            Descripcion = "Disco Mecánico Patatin",
                            Megas = 250L,
                            NumeroDeSerie = "788-fg-3",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Ordenadores.Ordenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Ordenadores");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Pedidos.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Componentes.Componente", b =>
                {
                    b.HasOne("MVC_ComponentesCodeFirst.Models.Ordenadores.Ordenador", "Ordenador")
                        .WithMany("Componentes")
                        .HasForeignKey("OrdenadorId");

                    b.Navigation("Ordenador");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Ordenadores.Ordenador", b =>
                {
                    b.HasOne("MVC_ComponentesCodeFirst.Models.Pedidos.Pedido", "Pedido")
                        .WithMany("Ordenadores")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Ordenadores.Ordenador", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("MVC_ComponentesCodeFirst.Models.Pedidos.Pedido", b =>
                {
                    b.Navigation("Ordenadores");
                });
#pragma warning restore 612, 618
        }
    }
}
